// Package testing includes testing tools shared by the examples.
package testing

import (
	"bufio"
	"fmt"
	"math"
	"os"
	"strconv"
	"strings"
	"testing"

	"github.com/gomlx/compute/dtypes"
	"github.com/gomlx/compute/shapes"
)

// ValidateEmbeddingTensor validates the values of a tensor.
// It checks the values of the first expectedSentenceLen tokens only, ignoring the padding in
// case gotSentencenLen > expectedSentenceLen.
func ValidateEmbeddingTensor(t *testing.T, got []float32, expected []float32, name string,
	batchSize, gotSentenceLen, expectedSentenceLen int) {

	gotHiddenDim := len(got) / batchSize / gotSentenceLen
	expectedHiddenDim := len(expected) / batchSize / expectedSentenceLen
	if gotHiddenDim == 0 || gotHiddenDim != expectedHiddenDim || gotSentenceLen < expectedSentenceLen {
		t.Fatalf("[%s] Shape mismatch: expected %d flat floats ([%d, %d, %d]?), got %d ([%d, %d, %d])",
			name, len(expected), batchSize, expectedSentenceLen, expectedHiddenDim,
			len(got), batchSize, gotSentenceLen, gotHiddenDim)
	}

	// Find mapping from expected indices to got indices.
	expectedShape := shapes.Make(dtypes.Float32, batchSize, expectedSentenceLen, expectedHiddenDim)
	gotShape := shapes.Make(dtypes.Float32, batchSize, gotSentenceLen, gotHiddenDim)
	gotStrides := gotShape.Strides()
	gotFlatIdxFn := func(indices []int) int {
		flatIdx := 0
		for i, idx := range indices {
			flatIdx += idx * gotStrides[i]
		}
		return flatIdx
	}

	var sumAbsDiff, sumAbsExpected float64
	const minRelDenominator = 0.2
	for flatIdx, expectedIndices := range expectedShape.Iter() {
		expectValue := float64(expected[flatIdx])
		gotValueF64 := float64(got[gotFlatIdxFn(expectedIndices)])
		absDiff := math.Abs(gotValueF64 - expectValue)
		sumAbsDiff += absDiff
		sumAbsExpected += math.Abs(expectValue)
	}
	meanAbsDiff := sumAbsDiff / float64(len(got))
	meanAbsExpected := sumAbsExpected / float64(len(got))

	var maxRelDiff float64
	var maxRelDiffIdx int
	for flatIdx, expectedIndices := range expectedShape.Iter() {
		expectValue := float64(expected[flatIdx])
		gotValueF64 := float64(got[gotFlatIdxFn(expectedIndices)])
		absDiff := math.Abs(gotValueF64 - expectValue)
		relDenominator := math.Max(math.Abs(expectValue), math.Abs(gotValueF64))
		relDenominator = max(relDenominator, meanAbsExpected)
		relDiff := absDiff / relDenominator
		if relDiff > maxRelDiff {
			maxRelDiff = relDiff
			maxRelDiffIdx = flatIdx
		}
	}

	maxRelTolerance := 5.0
	meanTolerance := 0.1

	if maxRelDiff > maxRelTolerance || meanAbsDiff >= meanTolerance*meanAbsExpected {
		t.Errorf("[%s] Mismatch in values: Max rel diff: %.3g at idx %d (ex %f, got %f) / "+
			"Mean abs diff: %.3g (== %.1f%% of the mean absolute values %.3g)",
			name, maxRelDiff, maxRelDiffIdx, expected[maxRelDiffIdx], got[maxRelDiffIdx],
			meanAbsDiff, 100*meanAbsDiff/meanAbsExpected, meanAbsExpected)
		for flatIdx, expectedIndices := range expectedShape.Iter() {
			expectValue := float64(expected[flatIdx])
			gotValueF64 := float64(got[gotFlatIdxFn(expectedIndices)])
			if flatIdx > 10 && flatIdx < len(expected)-10 {
				continue
			}
			fmt.Printf("\t- Value #%d:\tgot %.3g,\t expected %.3g\n", flatIdx, gotValueF64, expectValue)
		}
	} else {
		t.Logf("[%s] Match! Max rel diff: %.3g, Mean abs diff: %.3g (== %.1f%% of %.3g is the mean absolute)",
			name, maxRelDiff, meanAbsDiff, 100*meanAbsDiff/meanAbsExpected, meanAbsExpected)
	}
}

// ReadPythonEmbeddingsList returns all the embedding values written as text as a large []float32.
// It's up to the caller to split it according to the expected shape.
//
// It's called "Python" because these embeddings are generated by the test python scripts in internal/py.
func ReadPythonEmbeddingsList(path string) ([]float32, error) {
	file, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer file.Close()

	var results []float32
	scanner := bufio.NewScanner(file)
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		val, err := strconv.ParseFloat(line, 32)
		if err != nil {
			return nil, fmt.Errorf("failed to parse float: %v", err)
		}
		results = append(results, float32(val))
	}
	return results, scanner.Err()
}
