// Copyright 2026 The GoMLX Authors. SPDX-License-Identifier: Apache-2.0

package sam2

import (
	"fmt"
	"image"
	"image/color"
	"sort"

	"github.com/gomlx/compute"
	"github.com/gomlx/compute/dtypes"
	modelimage "github.com/gomlx/go-huggingface/models/image"
	. "github.com/gomlx/gomlx/core/graph"
	"github.com/gomlx/gomlx/core/tensors"
	"github.com/gomlx/gomlx/core/tensors/images"
	"github.com/gomlx/gomlx/ml/model"
)

// PointLabel indicates whether a point is foreground (positive) or background (negative).
type PointLabel int

const (
	LabelBackground PointLabel = 0
	LabelForeground PointLabel = 1
)

// PromptPoint defines a coordinate and its intent.
type PromptPoint struct {
	X, Y  int
	Label PointLabel
}

// PromptBox defines a bounding box for targeting objects.
type PromptBox struct {
	MinX, MinY int
	MaxX, MaxY int
}

// SegmentationOptions consolidates the inputs for the lightweight mask decoder.
type SegmentationOptions struct {
	Points []PromptPoint
	Boxes  []PromptBox

	// MultiMaskOutput controls whether the model returns multiple ambiguous masks
	// (e.g., sub-part, part, whole) or just the single best mask.
	MultiMaskOutput bool
}

// Segmentation represents a single valid segmentation mask hypothesis generated by the decoder.
type Segmentation struct {
	// Mask is represented as a standard grey/binary image.Image scaled to the original image dimensions.
	// Pixels inside the mask have value 255, and outside have value 0.
	Mask     image.Image
	IoUScore float32
}

// Segmenter uses SAM2 model to segment images.
type Segmenter struct {
	backend        compute.Backend
	model          *Model
	store          *model.Store
	config         *Config
	execMultimask  *model.Exec
	execSinglemask *model.Exec
}

// NewSegmenter initializes a predictor using the underlying SAM2 model definition.
func NewSegmenter(backend compute.Backend, modelObj *Model) (*Segmenter, error) {
	if backend == nil {
		var err error
		backend, err = compute.New()
		if err != nil {
			return nil, err
		}
	}
	store := model.NewStore()
	if err := modelObj.LoadStore(backend, store); err != nil {
		return nil, fmt.Errorf("failed to load model weights: %w", err)
	}

	s := &Segmenter{
		backend: backend,
		model:   modelObj,
		store:   store,
		config:  modelObj.Config,
	}

	// Compile the multimask executor
	execMultimask, err := model.NewExec(backend, store, func(scope *model.Scope, rawImage, inputPoints, inputLabels *Node) []*Node {
		mean := []float64{0.485, 0.456, 0.406}
		std := []float64{0.229, 0.224, 0.225}
		preprocessed := modelimage.PreprocessGraph(rawImage, 1024, 1024, mean, std)
		predMasks, states := Forward(scope, preprocessed, inputPoints, inputLabels, nil, nil, s.config, true)
		return []*Node{predMasks, states.IoUScores}
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create multimask executor: %w", err)
	}
	s.execMultimask = execMultimask

	// Compile the singlemask executor
	execSinglemask, err := model.NewExec(backend, store, func(scope *model.Scope, rawImage, inputPoints, inputLabels *Node) []*Node {
		mean := []float64{0.485, 0.456, 0.406}
		std := []float64{0.229, 0.224, 0.225}
		preprocessed := modelimage.PreprocessGraph(rawImage, 1024, 1024, mean, std)
		predMasks, states := Forward(scope, preprocessed, inputPoints, inputLabels, nil, nil, s.config, false)
		return []*Node{predMasks, states.IoUScores}
	})
	if err != nil {
		return nil, fmt.Errorf("failed to create singlemask executor: %w", err)
	}
	s.execSinglemask = execSinglemask

	return s, nil
}

// Segment infers the segmentation masks for the given image and prompts.
func (p *Segmenter) Segment(img image.Image, options *SegmentationOptions) ([]Segmentation, error) {
	ptsArray, labelsArray := options.toPointsAndLabels()

	imgTensor := images.ToTensor(dtypes.Float32).Single(img)
	ptsTensor := tensors.FromValue(ptsArray)
	labelsTensor := tensors.FromValue(labelsArray)
	defer imgTensor.MustFinalizeAll()
	defer ptsTensor.MustFinalizeAll()
	defer labelsTensor.MustFinalizeAll()

	var exec *model.Exec
	if options.MultiMaskOutput {
		exec = p.execMultimask
	} else {
		exec = p.execSinglemask
	}

	outputs, err := exec.Call(imgTensor, ptsTensor, labelsTensor)
	if err != nil {
		return nil, fmt.Errorf("failed to run inference: %w", err)
	}
	predMasksTensor := outputs[0]
	iouScoresTensor := outputs[1]
	defer predMasksTensor.MustFinalizeAll()
	defer iouScoresTensor.MustFinalizeAll()

	masksVal := predMasksTensor.Value().([][][][][]float32)
	scoresVal := iouScoresTensor.Value().([][][]float32)

	var segmentations []Segmentation
	numMasks := len(scoresVal[0][0])
	bounds := img.Bounds()
	w, h := bounds.Dx(), bounds.Dy()

	for m := 0; m < numMasks; m++ {
		maskImg := resizeMask(masksVal[0][0][m], w, h)
		segmentations = append(segmentations, Segmentation{
			Mask:     maskImg,
			IoUScore: scoresVal[0][0][m],
		})
	}

	// Sort descending by IoU score
	sort.Slice(segmentations, func(i, j int) bool {
		return segmentations[i].IoUScore > segmentations[j].IoUScore
	})

	return segmentations, nil
}

func (options *SegmentationOptions) toPointsAndLabels() ([][][][]float32, [][][]int32) {
	var pts [][]float32
	var lbls []int32
	for _, p := range options.Points {
		pts = append(pts, []float32{float32(p.X), float32(p.Y)})
		lbls = append(lbls, int32(p.Label))
	}
	for _, b := range options.Boxes {
		pts = append(pts, []float32{float32(b.MinX), float32(b.MinY)})
		lbls = append(lbls, 2)
		pts = append(pts, []float32{float32(b.MaxX), float32(b.MaxY)})
		lbls = append(lbls, 3)
		pts = append(pts, []float32{0, 0})
		lbls = append(lbls, -1)
	}
	if len(pts) == 0 {
		pts = append(pts, []float32{0, 0})
		lbls = append(lbls, -1)
	}
	pts4D := [][][][]float32{[][][]float32{pts}}
	lbls3D := [][][]int32{[][]int32{lbls}}
	return pts4D, lbls3D
}

func resizeMask(logits [][]float32, targetW, targetH int) image.Image {
	img := image.NewGray(image.Rect(0, 0, targetW, targetH))
	h := len(logits)
	w := len(logits[0])
	for y := range targetH {
		srcY := y * h / targetH
		for x := range targetW {
			srcX := x * w / targetW
			val := byte(0)
			if logits[srcY][srcX] > 0 {
				val = 255
			}
			img.SetGray(x, y, color.Gray{Y: val})
		}
	}
	return img
}
